---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: nginx
  chart:
    git: ssh://git@github.com/pmialon/flux-get-started
    ref: master
    path: charts/nginx
  values:
    image:
      tag: "1234567890"
