---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: nginx-test
  chart:
    git: https://github.com/pmialon/flux-get-started.git
    ref: master
    path: charts/nginx
