---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: ghost
  chart:
    git: https://github.com/helm/helm.git
    ref: master
    path: helm/docs/examples/nginxs
